name: Check

on:
  push:
    paths:
      - '**.clj'
      - '**.cljc'
      - '**.cljs'
      - '**.bb'
      - '**.edn'
      - '**.repl'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: ['11', '17', '21']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: '1.11.1.1208'
          bb: '1.3.186'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-

      - run: clojure -X:dev user/xr! '{:path "check"}'

      - run: clojure -A:dev -X cognitect.test-runner.api/test

      - run: npm install

      - run: npx shadow-cljs compile test && node out/test.js

      - run: bb test/run.bb
